"""Parse and apply user overrides from markdown files.

User overrides let people manually adjust validity scores, rankings,
verdicts, and source trust scores that were generated by the pipeline.
Overrides are persisted as markdown blockquotes and honoured on re-render.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from makeragents.schemas import Opportunity, ScoreSet, Verdict

_OVERRIDE_FIELDS = frozenset({"validity_score", "ranking", "verdict", "source_trust"})

# ---------------------------------------------------------------------------
# Regex for parsing override blocks
# ---------------------------------------------------------------------------
# Expected format:
#   > User Override:
#   > validity_score changed from 61 to 75.
#   > Reason: user manually confirmed source relevance.
_OVERRIDE_PATTERN = re.compile(
    r"> User Override:\r?\n"
    r"> (validity_score|ranking|verdict|source_trust) changed from (.+?) to (.+?)\.\r?\n"
    r"> Reason: (.+)",
    re.MULTILINE,
)

_APPLIED_OVERRIDE_MARKER = "**User Override Applied:**"


# ---------------------------------------------------------------------------
# Data class
# ---------------------------------------------------------------------------


@dataclass
class UserOverride:
    """A single user override parsed from a markdown file.

    Attributes:
        field_name: One of ``validity_score``, ``ranking``, ``verdict``,
            or ``source_trust``.
        old_value: The original value as a string (as written in the markdown).
        new_value: The replacement value as a string.
        reason: Free-text reason supplied by the user.
        source: Optional file path or identifier showing where the override
            was read from.
    """

    field_name: str
    old_value: str
    new_value: str
    reason: str
    source: str = ""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def parse_overrides(markdown_text: str, *, source: str = "") -> list[UserOverride]:
    """Parse all user-override blockquotes from *markdown_text*.

    Returns an empty list when no overrides are found.  Malformed blocks
    that look like overrides but don't match the expected pattern are
    silently skipped.
    """
    return [
        UserOverride(
            field_name=m.group(1),
            old_value=m.group(2).strip(),
            new_value=m.group(3).strip(),
            reason=m.group(4).strip(),
            source=source,
        )
        for m in _OVERRIDE_PATTERN.finditer(markdown_text)
        # Defense-in-depth: regex already constrains field_name, but validate anyway.
        if m.group(1) in _OVERRIDE_FIELDS
    ]


def apply_score_overrides(
    scores: ScoreSet, overrides: list[UserOverride]
) -> ScoreSet:
    """Return a new :class:`ScoreSet` with overridden fields applied.

    Only ``validity_score`` and ``ranking`` overrides are acted upon here:

    * ``validity_score`` → replace the score value and **recalculate**
      ``rank_score`` from the updated component scores.
    * ``ranking`` → force ``rank_score`` to the user-supplied value
      (no recalculation of other scores).

    Unrecognised or unapplicable overrides are silently ignored.
    """
    score_overrides = [o for o in overrides if o.field_name in ("validity_score", "ranking")]
    if not score_overrides:
        return scores  # no changes needed

    values: dict[str, float] = scores.model_dump()

    # Separate ranking overrides — they are applied last so validity
    # recalculation doesn't overwrite an explicit ranking override.
    ranking_override: float | None = None

    for ov in score_overrides:
        if ov.field_name == "validity_score":
            try:
                values["validity_score"] = float(ov.new_value)
            except ValueError:
                continue
        elif ov.field_name == "ranking":
            try:
                ranking_override = float(ov.new_value)
            except ValueError:
                continue

    if ranking_override is not None:
        values["rank_score"] = ranking_override
    else:
        # Recalculate if validity changed (or just always recalc to be safe).
        values["rank_score"] = ScoreSet.calculate_rank_score(
            people_helped_score=values["people_helped_score"],
            severity_score=values["severity_score"],
            validity_score=values["validity_score"],
            intervention_ease_score=values["intervention_ease_score"],
            harm_risk_score=values["harm_risk_score"],
            ability_to_act_score=values["ability_to_act_score"],
        )

    # Coerce all values back into ScoreValue range before constructing.
    for key in (
        "validity_score",
        "maker_score",
        "taker_score",
        "people_helped_score",
        "severity_score",
        "impact_score",
        "intervention_ease_score",
        "harm_risk_score",
        "ability_to_act_score",
        "rank_score",
    ):
        values[key] = max(0.0, min(100.0, values[key]))

    return ScoreSet(**values)


def apply_verdict_override(
    opportunity: Opportunity, overrides: list[UserOverride],
) -> Verdict | None:
    """Return the user-overridden :class:`Verdict` for *opportunity*.

    Falls back to ``opportunity.verdict`` when no valid verdict override
    applies.  Only the *last* ``verdict`` override in the list is used.
    """
    for ov in reversed(overrides):
        if ov.field_name == "verdict":
            try:
                return Verdict(ov.new_value)
            except ValueError:
                continue
    return opportunity.verdict  # fallback to original


def apply_trust_overrides(
    trust_score: float, overrides: list[UserOverride],
) -> float:
    """Return an updated trust score after applying ``source_trust`` overrides.

    Only the *last* ``source_trust`` override in the list is used.  The
    returned value is clamped to [0, 100].
    """
    for ov in reversed(overrides):
        if ov.field_name == "source_trust":
            try:
                return max(0.0, min(100.0, float(ov.new_value)))
            except ValueError:
                continue
    return trust_score


def format_override_markdown(overrides: list[UserOverride]) -> str:
    """Format a list of applied overrides as a Markdown blockquote.

    Returns an empty string when *overrides* is empty.
    """
    if not overrides:
        return ""

    lines: list[str] = [f"> {_APPLIED_OVERRIDE_MARKER}"]
    for ov in overrides:
        lines.append(f"> - `{ov.field_name}`: {ov.old_value} → {ov.new_value}")
        if ov.reason:
            lines.append(f">   Reason: {ov.reason}")
    lines.append("")
    return "\n".join(lines)


def has_overrides(markdown_text: str) -> bool:
    """Return ``True`` when *markdown_text* contains user override blocks."""
    return bool(_OVERRIDE_PATTERN.search(markdown_text))


def strip_overrides(markdown_text: str) -> str:
    """Return *markdown_text* with user-override blocks removed.

    This is useful when regenerating a report to avoid duplicating
    the original override block (which will be re-emitted from the
    applied overrides).
    """
    return _OVERRIDE_PATTERN.sub("", markdown_text).strip()
